### ISSUE TITLE
Add suggestions for learning rust

### ISSUE THREAD

**Issue by matthewdarwin** [pinax-network/awesome-substreams#6]
Here are some suggestions:

https://www.lurklurk.org/effective-rust/
https://doc.rust-lang.org/book/second-edition/
https://www.youtube.com/watch?v=T_KrYLW4jw8&list=PLzMcBGfZo4-nyLTlSRBvo0zjSnCnqjHYQ
https://www.youtube.com/@NoBoilerplate

**Comment by aasseman** [comment]
Here's another one: https://fasterthanli.me/articles/a-half-hour-to-learn-rust
